export enum ZIndex {
    BackgroundDecals = -200,
    BackgroundEntities = -180,
    TerrainEntities = -160,
    TerrainDecals = -140,
    Entities = -130,
    AboveEntitiesDecals = -120,
    Shadows = -115,
    CharacterEntities = -110,
    PlayerEntities = -100,
    FrontEntities = -70,
    FrontDecals = -30,
    RegionEntities = -15,
    MarkerEntities = -10,
}
